version: "3"
services:
  db:
    image: "mysql:8.0.17"
    environment:
      MYSQL_DATABASE: epytodo
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3308:3306"
    volumes:
      - ./epytodo.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    restart: on-failure