version: "3"
services:
  db:
    image: "mysql"
    environment:
        MYSQL_ROOT_PASSWORD: "password"
        MYSQL_DATABASE: "epytodo"
    ports:
      - "3306:3306"
    volumes:
      - ./epytodo.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    restart: on-failure
